import { 
  Expense, 
  ExpenseCategory, 
  CostCenter, 
  Client, 
  SilageOrder, 
  Machinery, 
  CropSeason,
  Employee,
  FleetTeam,
  CompanyProfile,
  Supplier,
  InventoryItem,
  ServiceOrder,
  FuelLog,
  MaintenanceLog,
  BankAccount,
  ThirdPartySettlement
} from '../types';

export const DEFAULT_FORAGE_HARVESTER_LOGO = '';

export const INITIAL_COMPANY_PROFILE: CompanyProfile = {
  corporateName: 'Silagem Fácil',
  tradeName: 'Gestão de Silagem',
  cnpjCpf: '',
  stateRegistration: '',
  phone: '',
  email: '',
  loginEmail: '',
  zipCode: '',
  address: '',
  number: '',
  neighborhood: '',
  city: '',
  state: 'PR',
  activitySector: 'GESTÃO AGRÍCOLA',
  logoUrl: '',
};

export const INITIAL_CATEGORIES: ExpenseCategory[] = [
  {
    id: 'cat_combustivel',
    name: 'Combustível & Arla (Diesel)',
    color: '#d97706',
    icon: 'Fuel',
    description: 'Óleo diesel S10, S500 e aditivos para tratores e caminhões',
  },
  {
    id: 'cat_manutencao',
    name: 'Manutenção & Peças',
    color: '#dc2626',
    icon: 'Wrench',
    description: 'Reparos em ensiladeiras, facas, contra-facas, correias, filtros e mecânica',
  },
  {
    id: 'cat_insumos',
    name: 'Insumos Agrícolas',
    color: '#16a34a',
    icon: 'Sprout',
    description: 'Sementes de milho/sorgo, adubos, defensivos, inoculante bacteriano e lona',
  },
  {
    id: 'cat_mao_de_obra',
    name: 'Mão de Obra & Diárias',
    color: '#0284c7',
    icon: 'Users',
    description: 'Operadores de trator, diaristas de colheita/compactação, encargos e folha',
  },
  {
    id: 'cat_frete',
    name: 'Frete & Logística',
    color: '#7c3aed',
    icon: 'Truck',
    description: 'Transporte de silagem da lavoura ao silo ou entrega ao cliente',
  },
  {
    id: 'cat_alimentacao',
    name: 'Alimentação & Campo',
    color: '#ea580c',
    icon: 'Utensils',
    description: 'Marmitas, café, água e suporte à equipe em campo durante o corte',
  },
  {
    id: 'cat_lona_embalagem',
    name: 'Lona, Fita & Embalagens',
    color: '#0d9488',
    icon: 'Layers',
    description: 'Lonas dupla face 200 micras, fita adesiva de vedação e sacos de silagem',
  },
  {
    id: 'cat_arrendamento',
    name: 'Arrendamento & Terra',
    color: '#854d0e',
    icon: 'MapPin',
    description: 'Aluguel de terras para plantio de silagem e taxas rurais',
  },
  {
    id: 'cat_administrativo',
    name: 'Administrativo & Comercial',
    color: '#475569',
    icon: 'Briefcase',
    description: 'Despesas de escritório, software, visitas a clientes, telefonia e consultoria',
  },
  {
    id: 'cat_outros',
    name: 'Outras Despesas',
    color: '#6b7280',
    icon: 'CircleDot',
    description: 'Despesas eventuais e miudezas da operação',
  },
];

export const INITIAL_COST_CENTERS: CostCenter[] = [
  {
    id: 'cc_colheita',
    name: 'Frente de Colheita / Ensiladeiras',
    type: 'maquinario',
  },
  {
    id: 'cc_transporte',
    name: 'Transporte & Caminhões',
    type: 'maquinario',
  },
  {
    id: 'cc_compactacao',
    name: 'Compactação & Fechamento de Silo',
    type: 'maquinario',
  },
  {
    id: 'cc_oficina',
    name: 'Oficina & Manutenção Geral',
    type: 'geral',
  },
  {
    id: 'cc_administrativo',
    name: 'Administração & Base Operacional',
    type: 'geral',
  },
];

export const INITIAL_SEASONS: CropSeason[] = [];

// Clean Zeroed Arrays for Manual Entry
export const INITIAL_MACHINERIES: Machinery[] = [];
export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-alisson-pagotto',
    name: 'ALISSON PAGOTTO',
    role: 'Motorista de Caminhão',
    roles: ['Motorista de Caminhão'],
    cargoId: 'cargo-motorista-caminhao',
    cargo_setor: 'TRANSPORTE & LOGÍSTICA',
    permissions: {
      financeiro: false,
      frotas: true,
      rh: false,
      estoque: false,
      empresa: false,
    },
    permissoes: {
      financeiro: false,
      frotas: true,
      rh: false,
      estoque: false,
      empresa: false,
    },
    phone: '(19) 99876-5432',
    cpf: '123.456.789-00',
    registrationType: 'Funcionário',
    contractType: 'Registrado (CLT)',
    regime_contratacao: 'Registrado (CLT)',
    active: true,
    status: 'ativo',
  },
];
export const INITIAL_FLEET_TEAMS: FleetTeam[] = [];
export const INITIAL_SUPPLIERS: Supplier[] = [];
export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'prod_diesel_s10',
    code: 'COMB-S10',
    name: 'Diesel S10',
    nome: 'Diesel S10',
    nome_comercial: 'Diesel S10',
    category: 'Combustível & Arla',
    categoria: 'Combustível & Arla',
    quantity: 0,
    quantidade_atual: 0,
    unit: 'L',
    unidade_medida: 'L',
    minQuantity: 2000,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'Tanque Fazenda (Pátio Central)',
  },
  {
    id: 'prod_diesel_s500',
    code: 'COMB-S500',
    name: 'Diesel S500',
    nome: 'Diesel S500',
    nome_comercial: 'Diesel S500',
    category: 'Combustível & Arla',
    categoria: 'Combustível & Arla',
    quantity: 0,
    quantidade_atual: 0,
    unit: 'L',
    unidade_medida: 'L',
    minQuantity: 1500,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'Tanque Fazenda (Oficina)',
  },
  {
    id: 'prod_arla_32_granel',
    code: 'ARLA-GRANEL',
    name: 'Arla 32 (Granel/Litro)',
    nome: 'Arla 32 (Granel/Litro)',
    nome_comercial: 'Arla 32 (Granel/Litro)',
    category: 'Combustível & Arla',
    categoria: 'Combustível & Arla',
    quantity: 0,
    quantidade_atual: 0,
    unit: 'L',
    unidade_medida: 'L',
    minQuantity: 100,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'Barracão de Abastecimento',
  },
  {
    id: 'prod_arla_32_galao_20l',
    code: 'ARLA-GAL20L',
    name: 'Arla 32 (Galão 20L)',
    nome: 'Arla 32 (Galão 20L)',
    nome_comercial: 'Arla 32 (Galão 20L)',
    category: 'Combustível & Arla',
    categoria: 'Combustível & Arla',
    quantity: 0,
    quantidade_atual: 0,
    unit: 'un',
    unidade_medida: 'un',
    minQuantity: 5,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    gallonSizeLiters: 20,
    volume_litros_embalagem: 20,
    location: 'Almoxarifado Principal',
  },
  // ========================================================
  // CARGA INICIAL DE SERVIÇOS E MÃOS DE OBRA NO ESTOQUE (MANDATÓRIO EM CAIXA ALTA)
  // tipo_item: 'SERVIÇO' e categorias oficiais por especialidade
  // ========================================================
  {
    id: 'srv_recapagem_pneu',
    code: 'SRV-REC-PNEU',
    codigo_produto: 'SRV-REC-PNEU',
    name: 'SERVIÇO DE RECAPAGEM DE PNEU',
    nome: 'SERVIÇO DE RECAPAGEM DE PNEU',
    nome_comercial: 'SERVIÇO DE RECAPAGEM DE PNEU',
    category: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    categoria: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    tipo_item: 'SERVIÇO',
    unit: 'UN',
    unidade_medida: 'UN',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 780,
    preco_venda_varejo: 780,
    preco_venda: 780,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_recauchutagem_pneu',
    code: 'SRV-RECAUCH-PNEU',
    codigo_produto: 'SRV-RECAUCH-PNEU',
    name: 'SERVIÇO DE RECAUCHUTAGEM DE PNEU',
    nome: 'SERVIÇO DE RECAUCHUTAGEM DE PNEU',
    nome_comercial: 'SERVIÇO DE RECAUCHUTAGEM DE PNEU',
    category: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    categoria: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    tipo_item: 'SERVIÇO',
    unit: 'UN',
    unidade_medida: 'UN',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 650,
    preco_venda_varejo: 650,
    preco_venda: 650,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_remoldagem_pneu',
    code: 'SRV-REMOLD-PNEU',
    codigo_produto: 'SRV-REMOLD-PNEU',
    name: 'SERVIÇO DE REMOLDAGEM DE PNEU (REMOLD)',
    nome: 'SERVIÇO DE REMOLDAGEM DE PNEU (REMOLD)',
    nome_comercial: 'SERVIÇO DE REMOLDAGEM DE PNEU (REMOLD)',
    category: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    categoria: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    tipo_item: 'SERVIÇO',
    unit: 'UN',
    unidade_medida: 'UN',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 450,
    preco_venda_varejo: 450,
    preco_venda: 450,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_vulcanizacao_pneu',
    code: 'SRV-VULC-PNEU',
    codigo_produto: 'SRV-VULC-PNEU',
    name: 'SERVIÇO DE VULCANIZAÇÃO DE PNEU',
    nome: 'SERVIÇO DE VULCANIZAÇÃO DE PNEU',
    nome_comercial: 'SERVIÇO DE VULCANIZAÇÃO DE PNEU',
    category: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    categoria: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    tipo_item: 'SERVIÇO',
    unit: 'UN',
    unidade_medida: 'UN',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 120,
    preco_venda_varejo: 120,
    preco_venda: 120,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_grooving_pneu',
    code: 'SRV-GROOVING',
    codigo_produto: 'SRV-GROOVING',
    name: 'SERVIÇO DE GROOVING (FRISAGEM / SULCAMENTO DE PNEU)',
    nome: 'SERVIÇO DE GROOVING (FRISAGEM / SULCAMENTO DE PNEU)',
    nome_comercial: 'SERVIÇO DE GROOVING (FRISAGEM / SULCAMENTO DE PNEU)',
    category: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    categoria: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    tipo_item: 'SERVIÇO',
    unit: 'UN',
    unidade_medida: 'UN',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 80,
    preco_venda_varejo: 80,
    preco_venda: 80,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_conserto_camara',
    code: 'SRV-CONS-CAMARA',
    codigo_produto: 'SRV-CONS-CAMARA',
    name: 'SERVIÇO DE CONSERTO DE CÂMARA DE AR',
    nome: 'SERVIÇO DE CONSERTO DE CÂMARA DE AR',
    nome_comercial: 'SERVIÇO DE CONSERTO DE CÂMARA DE AR',
    category: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    categoria: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    tipo_item: 'SERVIÇO',
    unit: 'UN',
    unidade_medida: 'UN',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 45,
    preco_venda_varejo: 45,
    preco_venda: 45,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_troca_valvula',
    code: 'SRV-TROCA-VALV',
    codigo_produto: 'SRV-TROCA-VALV',
    name: 'SERVIÇO DE TROCA DE VÁLVULA / COMPLEMENTO',
    nome: 'SERVIÇO DE TROCA DE VÁLVULA / COMPLEMENTO',
    nome_comercial: 'SERVIÇO DE TROCA DE VÁLVULA / COMPLEMENTO',
    category: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    categoria: 'SERVIÇOS MÃO DE OBRA BORRACHARIA',
    tipo_item: 'SERVIÇO',
    unit: 'UN',
    unidade_medida: 'UN',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 25,
    preco_venda_varejo: 25,
    preco_venda: 25,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_mo_mecanico',
    code: 'SRV-MO-MEC',
    codigo_produto: 'SRV-MO-MEC',
    name: 'SERVIÇO DE MÃO DE OBRA MECÂNICO',
    nome: 'SERVIÇO DE MÃO DE OBRA MECÂNICO',
    nome_comercial: 'SERVIÇO DE MÃO DE OBRA MECÂNICO',
    category: 'SERVIÇO',
    categoria: 'SERVIÇO',
    tipo_item: 'SERVIÇO',
    unit: 'HR',
    unidade_medida: 'HR',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_mo_eletricista_auto',
    code: 'SRV-MO-ELET-AUTO',
    codigo_produto: 'SRV-MO-ELET-AUTO',
    name: 'SERVIÇO DE MÃO DE OBRA ELETRICISTA (AUTOMOTIVO)',
    nome: 'SERVIÇO DE MÃO DE OBRA ELETRICISTA (AUTOMOTIVO)',
    nome_comercial: 'SERVIÇO DE MÃO DE OBRA ELETRICISTA (AUTOMOTIVO)',
    category: 'SERVIÇO',
    categoria: 'SERVIÇO',
    tipo_item: 'SERVIÇO',
    unit: 'HR',
    unidade_medida: 'HR',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_mo_funileiro',
    code: 'SRV-MO-FUNILEIRO',
    codigo_produto: 'SRV-MO-FUNILEIRO',
    name: 'SERVIÇO DE MÃO DE OBRA FUNILEIRO / LANTERNAGEM',
    nome: 'SERVIÇO DE MÃO DE OBRA FUNILEIRO / LANTERNAGEM',
    nome_comercial: 'SERVIÇO DE MÃO DE OBRA FUNILEIRO / LANTERNAGEM',
    category: 'SERVIÇO',
    categoria: 'SERVIÇO',
    tipo_item: 'SERVIÇO',
    unit: 'HR',
    unidade_medida: 'HR',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_mo_estofaria',
    code: 'SRV-MO-ESTOFARIA',
    codigo_produto: 'SRV-MO-ESTOFARIA',
    name: 'SERVIÇO DE MÃO DE OBRA ESTOFARIA / INTERIOR',
    nome: 'SERVIÇO DE MÃO DE OBRA ESTOFARIA / INTERIOR',
    nome_comercial: 'SERVIÇO DE MÃO DE OBRA ESTOFARIA / INTERIOR',
    category: 'SERVIÇO',
    categoria: 'SERVIÇO',
    tipo_item: 'SERVIÇO',
    unit: 'HR',
    unidade_medida: 'HR',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_mo_civil_pedreiro',
    code: 'SRV-MO-CIVIL',
    codigo_produto: 'SRV-MO-CIVIL',
    name: 'SERVIÇO DE MÃO DE OBRA CIVIL (REFORMA TIPO PEDREIRO)',
    nome: 'SERVIÇO DE MÃO DE OBRA CIVIL (REFORMA TIPO PEDREIRO)',
    nome_comercial: 'SERVIÇO DE MÃO DE OBRA CIVIL (REFORMA TIPO PEDREIRO)',
    category: 'SERVIÇO',
    categoria: 'SERVIÇO',
    tipo_item: 'SERVIÇO',
    unit: 'HR',
    unidade_medida: 'HR',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  },
  {
    id: 'srv_mo_eletricista_predial',
    code: 'SRV-MO-ELET-PRED',
    codigo_produto: 'SRV-MO-ELET-PRED',
    name: 'SERVIÇO DE MÃO DE OBRA ELETRICISTA PREDIAL E RESIDENCIAL',
    nome: 'SERVIÇO DE MÃO DE OBRA ELETRICISTA PREDIAL E RESIDENCIAL',
    nome_comercial: 'SERVIÇO DE MÃO DE OBRA ELETRICISTA PREDIAL E RESIDENCIAL',
    category: 'SERVIÇO',
    categoria: 'SERVIÇO',
    tipo_item: 'SERVIÇO',
    unit: 'HR',
    unidade_medida: 'HR',
    quantity: 0,
    quantidade_atual: 0,
    minQuantity: 0,
    unitCost: 0,
    preco_custo_inicial: 0,
    custo_nominal: 0,
    salePrice: 0,
    preco_venda_varejo: 0,
    preco_venda: 0,
    profitMargin: 0,
    location: 'PRESTAÇÃO DE SERVIÇOS',
    localizacao_fisica: 'PRESTAÇÃO DE SERVIÇOS',
    fiscalGroup: 'ISENTO',
    grupo_fiscal: 'ISENTO',
    ipiGroup: 'NAO TRIBUTADO',
    grupo_ipi: 'NAO TRIBUTADO',
    sem_gtin: true,
    hasNoGtin: true,
    barcode: 'SEM GTIN',
    codigo_barras: 'SEM GTIN',
  }
];
export const INITIAL_SERVICES: ServiceOrder[] = [];
export const INITIAL_FUEL_LOGS: FuelLog[] = [];
export const INITIAL_MAINTENANCE_LOGS: MaintenanceLog[] = [
  {
    id: 'maint_os_rhx3e15_30048',
    osNumber: 'OS-1001',
    orderNumber: '1001',
    title: 'Manutenção RHX3E15 - SR/WM PRANCHA 3E',
    date: '2026-09-30',
    completionDate: '2026-09-30',
    machineryId: '225a67f2-f65f-4e9d-a800-3da853facb38',
    machineryPlateOrName: 'RHX3E15 - SR/WM PRANCHA 3E',
    type: 'corretiva',
    serviceCategory: 'Solda, Funilaria & Estrutura',
    location: 'oficina_interna',
    executorType: 'equipe_propria',
    executorName: 'Mecânico Responsável',
    description: 'Ordem de Serviço de manutenção e revisão estrutural na prancha RHX3E15',
    workshopOrMechanic: 'Oficina Interna',
    partsCost: 0,
    laborCost: 300.48,
    totalCost: 300.48,
    currentHourMeterOrKm: 0,
    status: 'concluida',
    createdAt: '2026-09-30T00:00:00.000Z',
    companyId: 'e5b34cd7-aab4-4ce2-b5f0-45040c9ee7a4'
  }
];
export const INITIAL_EXPENSES: Expense[] = [];
export const INITIAL_CLIENTS: Client[] = [];
export const INITIAL_ORDERS: SilageOrder[] = [];
export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [];
export const INITIAL_SETTLEMENTS: ThirdPartySettlement[] = [];
